### ISSUE TITLE
Ultravox Import + Creating training bouts

### ISSUE THREAD

**Issue by BavoKempen** [DrCoffey/DeepSqueak#14]
Hey again,

While preparing all the data for training and trying to train with samples, I have bounced upon certain errors again for certain files. 
1) There seems to be an issue again with the import function of Ultravox, however, only for certain files similar to last time. Nonetheless, the error is different.
Error message: 
```
Error using audioread (line 135)
Range requested is greater than the total number of samples in the file. TotalSamples is 7405568.

Error in Import_From_Ultravox_Callback (line 58)
    Calls(i).Audio=audioread(AudioFile,round([windL windR]*rate),'native');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('Import_From_Ultravox_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```

2) Certain image bouts from files create again the following error. If I recall correctly, a similar issue happened last time when I was trying to train a network from scratch.
```

Index exceeds array bounds.

Error in vision.internal.cnn.generateAnchorBoxesInImage (line 63)
        outside = (x1 < 1) | (y1 < 1) | ((x1 + dim(1) - 1) > imageSize(2)) | ((y1 + dim(2) - 1) >
        imageSize(1));

Error in vision.internal.cnn.rpn.selectTrainingSamples (line 30)
[regionProposals, anchorLocInFeatureMap] = vision.internal.cnn.generateAnchorBoxesInImage(...

Error in vision.internal.cnn.rpn.RPNRegionReader/fillTrainingSamples (line 249)
                    s(i) = vision.internal.cnn.rpn.selectTrainingSamples(params, c{:});

Error in vision.internal.cnn.rpn.RPNRegionReader (line 158)
            this.TrainingSamples = fillTrainingSamples(this, groundTruth, params.UseParallel);

Error in vision.internal.cnn.rpn.RPNTrainingRegionDispatcher (line 64)
                vision.internal.cnn.rpn.RPNRegionReader(...

Error in fasterRCNNObjectDetector/createRPNTrainingDispatcher (line 665)
            dispatcher = vision.internal.cnn.rpn.RPNTrainingRegionDispatcher(...

Error in fasterRCNNObjectDetector.trainRPN (line 165)
            dispatcher = createRPNTrainingDispatcher(detector, groundTruth, opts, inputSize, params);

Error in trainFasterRCNNObjectDetector (line 289)
    [stage1Detector, rpn, info] = fasterRCNNObjectDetector.trainRPN(trainingData, rpn, options(1),
    iStageOneParams(params), checkpointSaver);

Error in TrainSqueakDetector (line 61)
detector = trainFasterRCNNObjectDetector(TrainingTables, layers, options, ...

Error in trainnew_Callback (line 44)
        [detector, layers, options] = TrainSqueakDetector(TrainingTables);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('trainnew_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```

Might it be that certain things were only adapted in the Master branch a couple of weeks ago and consequently were removed again by merging 1.2 branch into the master branch since similar problems occur.

Kind regards and all the best,

Bavo Kempen

**Comment by DrCoffey** [comment]
hmm, I'll take a look at what we updated. It looks like some of the detections are outside the range of the audio file. It is trying to make a box, but there isn't audio there to box. 

The fastest way for us to deal with this is if you could send one of the offending files over google drive or something.

**Comment by DrCoffey** [comment]
Hey Bavo,

I think the first error was because you have a call at the very end of the file. I think I fixed it, let me know if that worked!

-Kevin

**Comment by BavoKempen** [comment]
Hey Kevin, 

Unfortunately it did not work. 

Kind regards,

Bavo

**Comment by MxMarx** [comment]
I think I fixed the ultravox issue now.

Regarding network training, that issue might be the result of training images that are smaller than the neural network input layer. I think I've seen a similar issue before which went away after expanding the boxes around the shortest calls.

We're also in the process of hand-reviewing more files from different recording conditions in an effort to train networks that are more generalizable. If you have any human reviewed data, we'd be more than willing to add them to our training set.

-Russell

**Comment by DrCoffey** [comment]
Hey Bavo,

The error had to do with extremely short calls being too small for the network training. I think we fixed it, so let us know if that fixes your issue!

-Kevin

**Comment by DrCoffey** [comment]
Hey Bavo,

I'm going to close this particular issue, but if you run into any more issues, feel free to open another.

-Kevin

**Comment by BavoKempen** [comment]
Dear Kevin and Russell,

Firstly, my apologies for the very delayed answer, I did not find the time to test and run the aforementioned solutions to my problems.
Secondly, the import issue of Ultravox is solved indeed. Nonetheless, some error still occur with both creating image bouts and training which I will post in a new thread.

Kind regards, 

Bavo
